# A Gentle Introduction to Python - Numpy

Robin Thibaut, Ghent University, 2022

In [2]:
import numpy as np

numpy is a package that provides a high-performance multidimensional array object.

In [3]:
print("How to create a numpy array:")
print("Easiest way (by calling the numpy function)")
arr = np.array([1, 2, 3])  # Create a rank 1 array using a list
print(type(arr))  # Prints "<class 'numpy.ndarray'>"
print(arr.shape)  # Prints "(3,)"
print(arr[0], arr[1], arr[2])  # Prints "1 2 3"
print(arr[0:2])  # Works like in lists
print("")

How to create a numpy array:
Easiest way (by calling the numpy function)
<class 'numpy.ndarray'>
(3,)
1 2 3
[1 2]



In [4]:
arr = np.array([[1, 2, 3], [4, 5, 6]])  # Create a rank 2 array using lists of lists
print(arr.shape)  # Prints "(2, 3)"
print(arr[0, 0], arr[0, 1], arr[1, 0])  # Prints "1 2 4"
print("")

(2, 3)
1 2 4



Type of elements of the array can be specified:

In [5]:
float_arr = np.array(
    [1, 2, 3], dtype=np.float64
)  # float64 is the default type in python

If you want to change the type of an existing array (if you can):

In [6]:
int_arr = np.array([1.0, 2.0, 3.0])  # The input list has floats in it!
int_arr = int_arr.astype(np.int64)  # Now it uses int64 as datatype!

Arithmetic operations with arrays are applied element-wise:

In [7]:
print("Element-wise computation between arrays and single numbers: ")
x = np.array(
    [[1, 2], [3, 4]], dtype=np.float64
)  # Create a rank 2 array with floats in it!
y = np.array(
    [[5, 6], [7, 8]], dtype=np.float64
)  # Create another rank 2 array with floats in it!
# All of the following computations between arrays are element-wise!:
print(
    "Automatic element-wise computation between x and y; gives a new array with the same dimensions!"
)  # Works element wise and gives a new array back!
print(x + y)  # Elementwise sum;     [[ 6.0  8.0] [10.0 12.0]]
print(x - y)  # Elementwise difference; [[-4.0 -4.0] [-4.0 -4.0]]
print(x * y)  # Elementwise product; [[ 5. 12.] [21. 32.]]
print(x / y)  # Elementwise division; [[0.2        0.33333333] [0.42857143 0.5       ]]
print(x**y)  # Elementwise power;    [[  1.  64.] [ 2187. 8748.]]
# Other operations like +=, *=, -= and **= are also possible with numpy arrays!
print("")

Element-wise computation between arrays and single numbers: 
Automatic element-wise computation between x and y; gives a new array with the same dimensions!
[[ 6.  8.]
 [10. 12.]]
[[-4. -4.]
 [-4. -4.]]
[[ 5. 12.]
 [21. 32.]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[1.0000e+00 6.4000e+01]
 [2.1870e+03 6.5536e+04]]



In [8]:
print("Element-wise computation between arrays and single numbers: ")
print("Operations with single numbers: ")
x = np.array(
    [[1, 2], [3, 4]], dtype=np.float64
)  # Create a rank 2 array with floats in it!
print(x + 2)  # Elementwise sum with a number;       [[3. 4.] [5. 6.]]
print(x - 2)  # Elementwise substraction with a number; [[-1. 0.] [1. 2.]]
print(x * 2)  # Elementwise product with a number; [[2. 4.] [6. 8.]]
print(x / 2)  # Elementwise division by a number; [[0.5 1. ] [1.5 2. ]]
print(x**2)  # Elementwise exponentation by a number; [[ 1. 4.] [ 9. 16.]]

Element-wise computation between arrays and single numbers: 
Operations with single numbers: 
[[3. 4.]
 [5. 6.]]
[[-1.  0.]
 [ 1.  2.]]
[[2. 4.]
 [6. 8.]]
[[0.5 1. ]
 [1.5 2. ]]
[[ 1.  4.]
 [ 9. 16.]]


It is also possible to apply basic linear algebra computations like the dot product of two vectors! Only these<br>
linear algebra functions work on numpy arrays: 'dot', 'trace', 'transpose', 'linalg.inv' and 'linalg.diag'. (matrix<br>
multiplication, trace of a matrix, transpose of a matrix, inverse of a square matrix and diagonal)

In [9]:
print("")
print("Dealing with higher dimensions: ")
x = np.array([[1, 2], [3, 4]])  # Create a rank 2 array with ints in it!
y = np.array([[5, 6], [7, 8]])  # Create another rank 2 array with ints in it!
v = np.array([9, 10])  # Create a rank 1 array with ints in it!
w = np.array([11, 12])  # Create another rank 1 array with ints in it!


Dealing with higher dimensions: 


User 'dot' to compute the inner product of two vectors (they must have the same number of elements):

In [12]:
print("The dot product of two vectors: (result is a number) ")
print(v.dot(w))  # Prints 219
print("")
print(
    "The dot product of two arrays; works just like the multiplication of matrices: "
)  # Works element-wise on the two arrays and gives an array back!
print(x.dot(v))  # Prints [29 67]
print("")
print(
    "Using transpose function 'T' on x to compute the matrix product of x and y: "
)  # Works element-wise on the two arrays and gives an array back!
print(x.dot(y))  # Prints [[19 22] [43 50]]
# The transpose function 'T' is used to transpose an array:
print("")
print("Using T on x to transpose it: ")  # Gives you a new array back!
print(x.T)  # Prints [[1 3] [2 4]]
# The linalg.inv function is used to invert a square matrix:
print("")
print("Using linalg.inv on x to invert it: ")  # Gives you a new array back!
print(np.linalg.inv(x))  # Prints [[-2.   1. ] [1.5 -0.5]]
# The linalg.diag function is used to extract the diagonals of an array:
y = np.array([[5, 6], [7, 8]])  # Create another rank 2 array with ints in it!
print("")
print(
    "Using diag on y to extract the diagonals of it: "
)  # Gives you a new array back!
print(np.diag(y))  # Prints [5 8]

The dot product of two vectors: (result is a number) 
219

The dot product of two arrays; works just like the multiplication of matrices: 
[29 67]

Using transpose function 'T' on x to compute the matrix product of x and y: 
[[19 22]
 [43 50]]

Using T on x to transpose it: 
[[1 3]
 [2 4]]

Using linalg.inv on x to invert it: 
[[-2.   1. ]
 [ 1.5 -0.5]]

Using linalg.diag on y to extract the diagonals of it: 
[5 8]
